name: VyOS v1.3.x LTS FULLCONENAT Release
permissions:
  contents: write
on:
  push:
    tags:
      - 'v1.3.*FULL*'

env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/
  BRANCH: equuleus
  BUILD_ARCH: amd64
  BUILD_BY: vyos-build-action@github.com
  BUILD_TYPE: release
  BUILD_VERSION: 1.3.3
  ARTIFACTS_DIR: artifacts
  WORKING_DIR: vyos-build
  STATUS_SUCCESS: "::set-output name=status::success"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: vyos/vyos-build:equuleus
      options: --workdir /vyos --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone Source Code
        run: |
          git clone -b $BRANCH --single-branch $GIT_CLONE_URL $WORKING_DIR
          cd $WORKING_DIR
          ./configure --architecture $BUILD_ARCH --build-by $BUILD_BY --build-type $BUILD_TYPE --version $BUILD_VERSION-FULLCONENAT
          mkdir -p ./$ARTIFACTS_DIR
          
      - name: Download deb from debian official
        run:  |
         set -eux
         cd vyos-build
         wget -P  packages/ http://http.us.debian.org/debian/pool/main/i/ipset/ipset_6.38-1.2_amd64.deb 
         wget -P  packages/ http://http.us.debian.org/debian/pool/main/i/ipset/libipset11_6.38-1.2_amd64.deb
    
      - name: Download kernel deb from my another repo
        uses: robinraju/release-downloader@v1.7
        with:
         repository: "debiansid/vyos-kernel-lts-build"
         tag: "5.4.234"
         fileName: "*.deb"
         out-file-path: "vyos-build/packages/"
       
      - name: Download iptables deb from my another repo
        uses: robinraju/release-downloader@v1.7
        with:
         repository: "debiansid/iptables-fullconenat"
         tag: "debian/1.8.2-4"
         fileName: "*.deb"
         out-file-path: "vyos-build/packages/"    
         
      - name: Build ISO Image
        id: iso
        working-directory: ./${{ env.WORKING_DIR }}
        run: |
          make iso && echo $STATUS_SUCCESS
          
          cp -f ./build/vyos-$BUILD_VERSION-FULLCONENAT-$BUILD_ARCH.iso ./$ARTIFACTS_DIR/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vyos-${{ env.BUILD_VERSION }}-FULLCONENAT-${{ env.BUILD_ARCH }}.iso
          path: ${{ env.WORKING_DIR }}/${{ env.ARTIFACTS_DIR }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps :
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: vyos-${{ env.BUILD_VERSION }}-FULLCONENAT-${{ env.BUILD_ARCH }}.iso
          
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: VyOS v${{ env.BUILD_VERSION }} LTS FULLCONENAT Release
          body: VyOS v${{ env.BUILD_VERSION }} LTS FULLCONENAT Release
          draft: false
          prerelease: false
          files: vyos-${{ env.BUILD_VERSION }}-FULLCONENAT-${{ env.BUILD_ARCH }}.iso
            
