name: VyOS v1.5 Rolling FULLCONENAT Release
permissions:
  contents: write
on:
  push:
    tags:
      - "v1.5*FULL*"

env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  BRANCH: current
  ARCHITECTURE: amd64
  BUILD_BY: vyos-build-action@github.com
  BUILD_TYPE: release
  VERSION: 1.5-rolling
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:current
      options: --workdir /vyos --privileged
   
    steps:
      
      - name: Clone source code
        run: git clone -b $BRANCH --single-branch $GIT_CLONE_URL

      - name: Download deb from upstream
        run: |
         set -eux
         cd vyos-build
         wget -P  packages/ http://http.us.debian.org/debian/pool/main/i/ipset/libipset13_7.17-1_amd64.deb
         wget -P  packages/ http://http.us.debian.org/debian/pool/main/i/ipset/ipset_7.17-1_amd64.deb 
    
      - name: Download kernel deb from my another repo
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "debiansid/vyos-kernel-rolling"
          latest: true
          fileName: "*.deb"
          out-file-path: "vyos-build/packages/"
       
      - name: Download iptables deb from my another repo
        uses: robinraju/release-downloader@v1.7
        with:
           repository: "debiansid/iptables-fullconenat"
           latest: true
           fileName: "*.deb"
           out-file-path: "vyos-build/packages/"

      - name: Build ISO
        working-directory: ./vyos-build
        run: |
          sudo make clean
          sudo ./build-vyos-image iso --architecture $ARCHITECTURE --build-by $BUILD_BY --build-type $BUILD_TYPE --version $VERSION-FULLCONENAT

      - name: ls
        run: |
         set -eux

         pwd
         ls -lah
         ls -lah vyos-build/build
      
 
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: vyos-build/build/vyos-${{ env.VERSION }}-*.iso
          body: |
             VyOS ${{ env.RELEASE_VERSION }} LTS
          draft: true
          prerelease: true


