name: VyOS v1.4.x nft fullcone Release
permissions:
  contents: write
on:
  push:
    tags:
      - "v1.4*nft*"

env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  BRANCH: sagitta
  ARCHITECTURE: amd64
  BUILD_BY: vyos-build-action@github.com
  BUILD_TYPE: release
  VERSION: 1.4.0
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:sagitta
      options: --workdir /vyos --privileged
   
    steps:
      
      - name: Clone source code
        run: git clone -b 1.4.0-epa1 --single-branch $GIT_CLONE_URL

      - name: Download kernel deb from my another repo
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "ruau/vyos-kernel-rolling"
          latest: false
          tag: "6.6.17"
          fileName: "*.deb"
          out-file-path: "vyos-build/packages/"
       
      - name: Download libnftnl deb from my another repo
        uses: robinraju/release-downloader@v1.7
        with:
           repository: "debiansid/libnftnl-fullcone"
           latest: true
           fileName: "*.deb"
           out-file-path: "vyos-build/packages/"

      - name: Download nftables deb from my another repo
        uses: robinraju/release-downloader@v1.7
        with:
           repository: "debiansid/nftables-fullcone"
           latest: true
           fileName: "*.deb"
           out-file-path: "vyos-build/packages/"
           
      - name: Build ISO
        working-directory: ./vyos-build
        run: |
          sudo make clean
          sudo ./build-vyos-image iso --architecture $ARCHITECTURE --build-by $BUILD_BY --build-type $BUILD_TYPE --version $VERSION-fullcone

      - name: ls
        run: |
         set -eux

         pwd
         ls -lah
         ls -lah vyos-build/build
      
 
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: vyos-build/build/vyos-${{ env.VERSION }}-*.iso
          body: |
             VyOS ${{ env.RELEASE_VERSION }} LTS
          draft: true
          prerelease: true


